version: '3.3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:5.7
    # command: mysql -h localhost -P 3306 --protocol=tcp -u root
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./db/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  www:
    build:
      context: .
      dockerfile: ./DockerFile2
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - redis
      - db
      - elasticsearch
    ports:
      - "3000:3000"
    links:
      - redis
      - db
      - elasticsearch


  sidekiq:
    build:
      context: .
      dockerfile: ./DockerFile2
    command: ["bundle", "exec", "sidekiq", "-q", "chat_create", "-q", "message_create", "-q", "message_update", "-q", "default"]
    depends_on:
      - redis 
    links:
      - redis

volumes:
  db-data: