version: '3.3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:5.7
    # command: mysql -h localhost -P 3306 --protocol=tcp -u root
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  www:
    build:
      context: .
      dockerfile: ./DockerFile2
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - redis
      - db
    ports:
      - "3000:3000"
    links:
      - redis
      - db


  sidekiq:
    build:
      context: .
      dockerfile: ./DockerFile2
    command: ["bundle", "exec", "sidekiq", "-q", "chat_create", "-q", "message_create", "-q", "default"]
    depends_on:
      - redis
    links:
      - redis

volumes:
  db-data: