version: '3.3'

# To access data postgres writes within container from host machine
volumes:
  postgres_data: {}

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: production
    depends_on:
      - db
      - redis
    # env_file: .docker/.env
    ports:
      - "3000:3000"