version: '3.3'

services:
  # db:
  #   image: postgres:11-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: $DB_PASSWORD
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  www:
    build:
      context: .
      dockerfile: ./DockerFile2
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - redis
    ports:
      - "3000:3000"
    links:
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: ./DockerFile2
    command: ["bundle", "exec", "sidekiq", "-q", "chat_create", "-q", "message_create", "-q", "default"]
    depends_on:
      - redis
    links:
      - redis
