default: &default
  adapter: redis
  url: redis://0.0.0.0:6380/15/ns

development:
  <<: *default
  channel_prefix: my_app

test:
  <<: *default
  channel_prefix: my_app

production:
  <<: *default
  channel_prefix: my_app