default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  port: 3306
  username: root
  # password: root
  protocol: tcp

development:
  <<: *default
  database: rails_dev

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  database: rails_production